splits:
  - prefix: "symfony-base/7.1-nginx-alpine"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php71-nginx-alpine.git"
  - prefix: "symfony-base/7.1-nginx"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php71-nginx.git"
  - prefix: "symfony-base/7.1-apache"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php71-apache.git"
  - prefix: "symfony-base/7.0-nginx-alpine"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php70-nginx-alpine.git"
  - prefix: "symfony-base/7.0-nginx"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php70-nginx.git"
  - prefix: "symfony-base/7.0-apache"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php70-apache.git"
  - prefix: "symfony-base/5.6-nginx-alpine"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php56-nginx-alpine.git"
  - prefix: "symfony-base/5.6-nginx"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php56-nginx.git"
  - prefix: "symfony-base/5.6-apache"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php56-apache.git"
  - prefix: "symfony-db/7.1-nginx-alpine"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php71-nginx-db-alpine.git"
  - prefix: "symfony-db/7.1-nginx"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php71-nginx-db.git"
  - prefix: "symfony-db/7.1-apache"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php71-apache-db.git"
  - prefix: "symfony-db/7.0-nginx-alpine"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php70-nginx-db-alpine.git"
  - prefix: "symfony-db/7.0-nginx"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php70-nginx-db.git"
  - prefix: "symfony-db/7.0-apache"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php70-apache-db.git"
  - prefix: "symfony-db/5.6-nginx-alpine"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php56-nginx-db-alpine.git"
  - prefix: "symfony-db/5.6-nginx"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php56-nginx-db.git"
  - prefix: "symfony-db/5.6-apache"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php56-apache-db.git"

origins:
  - ^master$
  - ^v\d+\.\d+\.\d+$
