splits:
  - prefix: "symfony-base/7.1-fpm-alpine"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php71-nginx-alpine.git"
  - prefix: "symfony-base/7.1-fpm"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php71-nginx.git"
  - prefix: "symfony-base/7.1-apache"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php71-apache.git"
  - prefix: "symfony-db/7.1-fpm-alpine"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php71-nginx-db-alpine.git"
  - prefix: "symfony-db/7.1-fpm"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php71-nginx-db.git"
  - prefix: "symfony-db/7.1-apache"
    target: "https://${GH_TOKEN}@github.com/hiskiwi/docker-symfony-php71-apache-db.git"

origins:
  - ^master$
  - ^v\d+\.\d+\.\d+$
