---
  sudo: required
  notifications:
    email: true
  services:
    - docker
  install:
    - sudo pip install docker-compose
    - |
      # General configuration
      stty cols 120
      # tfold is a helper to create folded reports
      tfold () {
          title=$1
          fold=$(echo $title | sed -r 's/[^-_A-Za-z\d]+/./g')
          shift
          echo -e "travis_fold:start:$fold\\n\\e[1;34m$title\\e[0m"
          bash -xc "$*" 2>&1 &&
              echo -e "\\e[32mOK\\e[0m $title\\n\\ntravis_fold:end:$fold" ||
              ( echo -e "\\e[41mKO\\e[0m $title\\n" && exit 1 )
      }
      export -f tfold
    - |
      run_tests () {
          set -e
          echo "$COMPONENTS" | parallel --gnu "tfold {} $PHPUNIT_X {}"
          tfold tty-group $PHPUNIT --group tty
      }
  script:
    - docker --version
    - docker-compose --version
    - tfold docker "cd docker && docker-compose build"
    - tfold devbox "cd devbox && docker-compose build"
