---
  sudo: required
  notifications:
    email: true
  services:
    - docker
  install:
    - sudo pip install docker-compose
  script:
    - docker --version
    - docker-compose --version
    - make
    - make test
