version: '2'

services:
    nginx:
        image: nginx:1-alpine
        volumes:
            - .:/srv:ro
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
        links:
            - php

    php:
        build: docker/php
        image: mykiwi/symfony-fast:7.0-fpm
        volumes:
            - .:/srv
            - /srv/var/cache
            - /srv/var/logs
            - /srv/var/sessions
