version: '2.1'

services:
    app:
        build: docker/php
        image: mykiwi/symfony-base:5.6-fpm
        working_dir: /srv
        volumes:
            - .:/srv
            - /srv/var/cache
            - /srv/var/logs
            - /srv/var/sessions
        command: php bin/console server:run 0.0.0.0:80
        environment:
            - SYMFONY_ENV=dev
        expose:
            - "80"
