version: '2'

services:
  http:
    image: nginx:1
    volumes:
      - .:/srv:ro
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build: docker/php
    image: mykiwi/symfony-base:5.6-fpm
    working_dir: /srv
    volumes:
      - .:/srv
