version: '2'

services:
  app:
    build: docker/php
    image: mykiwi/symfony-base:7.0-apache
    working_dir: /srv
    volumes:
      - ./docker/apache/dev.conf:/etc/apache2/sites-enabled/000-default.conf:ro
      - .:/srv
